"""empty message

Revision ID: 0ff9c436b59d
Revises: ad236fc2c202
Create Date: 2026-05-23 19:41:14.948992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff9c436b59d'
down_revision = 'ad236fc2c202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_message', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
