"""empty message

Revision ID: 163fa52cb4b1
Revises: 3b465370a940
Create Date: 2026-05-22 10:53:06.521399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163fa52cb4b1'
down_revision = '3b465370a940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption', sa.JSON(), nullable=True))
        batch_op.drop_column('use_ssl')
        batch_op.drop_column('use_tls')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_tls', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('use_ssl', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('encryption')

    # ### end Alembic commands ###
