"""empty message

Revision ID: 43a2989c4b74
Revises: 0ff9c436b59d
Create Date: 2026-05-23 04:22:00.873342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a2989c4b74'
down_revision = '0ff9c436b59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_message', schema=None) as batch_op:
        batch_op.drop_column('result')

    # ### end Alembic commands ###
