"""empty message

Revision ID: ad236fc2c202
Revises: 163fa52cb4b1
Create Date: 2026-05-22 11:11:27.132571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad236fc2c202'
down_revision = '163fa52cb4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_data', sa.JSON(), nullable=True))
        batch_op.drop_column('smtp_port')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_port', sa.INTEGER(), nullable=False))
        batch_op.drop_column('smtp_data')

    # ### end Alembic commands ###
